"""French course (for English and Russian speakers): grammar topics and units A1 → C1.

Titles are dicts {en, ru}. Explanations: content/fr/grammar/<topic>.{en,ru}.md ; drills: content/fr/drills/<topic>.txt
"""
from sel import ANY, COMP, M, NEED, NOQ, PARTITIVE, RX, V, VC, VCOMP, VL, W

PRES = ["pres"]
AUX = ("avoir", "être")


def T(en, ru):
    return {"en": en, "ru": ru}


TOPICS = [
    # ---------------- A1 ----------------
    dict(id="fr-sounds", level="A1", title=T("Sounds, spelling, liaison and elision", "Звуки, орфография, связывание и элизия")),
    dict(id="fr-etre", level="A1", title=T("Subject pronouns and être (to be)", "Личные местоимения и глагол être (быть)"),
         auto=V(PRES, lemmas=["être"]), tenses=PRES),
    dict(id="fr-articles", level="A1", title=T("Gender and the definite article (le, la, l', les)", "Род и определённый артикль (le, la, l', les)"),
         auto=W(["le", "la", "les", "l'"], options=["le", "la", "l'", "les"], pos=["DET"])),
    dict(id="fr-indef", level="A1", title=T("Un, une, des; plurals", "Неопределённый артикль un, une, des; множественное число"),
         auto=W(["un", "une", "des"], options=["un", "une", "des"], pos=["DET"])),
    dict(id="fr-adjectives", level="A1", title=T("Adjectives: agreement and position", "Прилагательные: согласование и место"),
         auto=ANY(M(["ADJ"], ["Gender=Fem"]), M(["ADJ"], ["Number=Plur"]))),
    dict(id="fr-avoir", level="A1", title=T("Avoir (to have), il y a, expressions with avoir", "Avoir (иметь), il y a и выражения с avoir"),
         auto=V(PRES, lemmas=["avoir"]), tenses=PRES),
    dict(id="fr-er-verbs", level="A1", title=T("Present tense: -er verbs", "Настоящее время: глаголы на -er"),
         auto=V(PRES, lemmas=["parler", "aimer", "habiter", "travailler", "regarder", "écouter", "chercher", "trouver", "donner",
                              "manger", "jouer", "chanter", "danser", "acheter", "appeler", "commencer", "arriver", "entrer",
                              "rester", "penser", "demander", "marcher", "passer", "porter", "laisser", "aider", "oublier",
                              "préparer", "fermer", "étudier", "visiter", "voyager", "téléphoner", "rentrer", "continuer"])),
    dict(id="fr-negation", level="A1", title=T("Negation: ne … pas, ne … jamais, ne … rien", "Отрицание: ne … pas, ne … jamais, ne … rien"),
         auto=NEED(W(["pas", "jamais", "rien", "plus", "personne"], pos=["ADV", "PRON"]), ["ne", "n'"])),
    dict(id="fr-questions", level="A1", title=T("Asking questions; question words", "Вопросы и вопросительные слова"),
         auto=NEED(W(["qui", "quoi", "où", "quand", "comment", "pourquoi", "combien", "quel", "quelle", "quels", "quelles"]), ["?"])),
    dict(id="fr-possessives", level="A1", title=T("Possessive adjectives (mon, ma, mes…)", "Притяжательные прилагательные (mon, ma, mes…)"),
         auto=W(["mon", "ma", "mes", "ton", "ta", "tes", "son", "sa", "ses", "notre", "nos", "votre", "vos", "leur", "leurs"], pos=["DET"])),
    dict(id="fr-demonstratives", level="A1", title=T("Ce, cet, cette, ces; prepositions of place", "Указательные ce, cet, cette, ces; предлоги места"),
         auto=W(["ce", "cet", "cette", "ces"], options=["ce", "cet", "cette", "ces"], pos=["DET"])),
    dict(id="fr-numbers", level="A1", title=T("Numbers, prices and the time", "Числа, цены и время"),
         auto=W(["deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "quinze", "vingt", "trente", "cent", "mille"], pos=["NUM"])),
    dict(id="fr-dates", level="A1", title=T("Days, months and dates", "Дни недели, месяцы, даты"),
         auto=W(["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche", "hier", "demain", "aujourd'hui"])),
    dict(id="fr-aller-venir", level="A1", title=T("Aller and venir; au, du; towns and countries", "Aller и venir; au, du; города и страны"),
         auto=ANY(V(PRES, lemmas=["aller", "venir"]), W(["au", "aux"], options=["au", "aux", "à la"])), tenses=PRES),
    dict(id="fr-futur-proche", level="A1", title=T("Near future (aller + inf.) and recent past (venir de)", "Ближайшее будущее (aller + инф.) и недавнее прошлое (venir de)"),
         auto=NEED(V(PRES, lemmas=["aller", "venir"]), ["vais", "vas", "va", "allons", "allez", "vont", "viens", "vient", "venons", "venez", "viennent"])),
    dict(id="fr-ir-re", level="A1", title=T("-ir and -re verbs; faire, prendre, mettre", "Глаголы на -ir и -re; faire, prendre, mettre"),
         auto=V(PRES, lemmas=["finir", "choisir", "réussir", "vendre", "attendre", "répondre", "entendre", "perdre", "rendre",
                              "faire", "prendre", "mettre", "dire", "lire", "écrire", "boire", "comprendre", "apprendre", "dormir", "partir", "sortir"])),
    dict(id="fr-modals", level="A1", title=T("Vouloir, pouvoir, devoir, savoir", "Vouloir, pouvoir, devoir, savoir"),
         auto=ANY(V(PRES, lemmas=["vouloir", "pouvoir", "devoir"]), VL("savoir", "connaître", PRES))),
    dict(id="fr-partitive", level="A1", title=T("The partitive: du, de la, des; quantities", "Частичный артикль du, de la, des; количество"),
         auto=PARTITIVE()),
    dict(id="fr-reflexive", level="A1", title=T("Pronominal (reflexive) verbs", "Возвратные (местоименные) глаголы"),
         auto=W(["me", "m'", "te", "t'", "se", "s'"], pos=["PRON"])),
    dict(id="fr-imperative", level="A1", title=T("The imperative", "Повелительное наклонение"), auto=NOQ(V(["imp"], morph_req=("Mood=Imp",))), tenses=["imp"]),
    dict(id="fr-weather", level="A1", title=T("Weather and seasons", "Погода и времена года"),
         auto=NEED(W(["fait", "pleut", "neige", "faisait", "pleuvait"]), ["il"])),
    dict(id="fr-comparatives", level="A1", title=T("Comparisons: plus, moins, aussi … que", "Сравнение: plus, moins, aussi … que"),
         auto=W(["plus", "moins", "aussi", "meilleur", "meilleure", "mieux"])),
    # ---------------- A2 ----------------
    dict(id="fr-pc-avoir", level="A2", title=T("Passé composé with avoir", "Passé composé с avoir"), auto=COMP("pc", aux=("avoir",)), tenses=["pc", "pp"]),
    dict(id="fr-pc-etre", level="A2", title=T("Passé composé with être; agreement", "Passé composé с être; согласование"), auto=COMP("pc", aux=("être",))),
    dict(id="fr-imparfait", level="A2", title=T("The imparfait", "Имперфект (imparfait)"), auto=V(["impf"]), tenses=["impf"]),
    dict(id="fr-pc-impf", level="A2", title=T("Passé composé or imparfait?", "Passé composé или imparfait?"), auto=VCOMP("impf", "pc", AUX)),
    dict(id="fr-cod", level="A2", title=T("Direct object pronouns (le, la, les)", "Местоимения — прямые дополнения (le, la, les)"),
         auto=W(["le", "la", "les"], options=["le", "la", "les"], pos=["PRON"])),
    dict(id="fr-coi", level="A2", title=T("Indirect object pronouns (lui, leur); pronoun order", "Косвенные дополнения (lui, leur); порядок местоимений"),
         auto=W(["lui", "leur"], options=["lui", "leur", "le", "les"], pos=["PRON"])),
    dict(id="fr-y-en", level="A2", title=T("The pronouns y and en", "Местоимения y и en"), auto=W(["y", "en"], options=["y", "en"], pos=["PRON"])),
    dict(id="fr-futur", level="A2", title=T("The simple future", "Простое будущее время (futur simple)"), auto=V(["fut"]), tenses=["fut"]),
    dict(id="fr-conditionnel", level="A2", title=T("The present conditional", "Условное наклонение (conditionnel présent)"), auto=V(["cond"]), tenses=["cond"]),
    dict(id="fr-relatives", level="A2", title=T("Relative pronouns: qui, que, où, dont", "Относительные местоимения qui, que, où, dont"),
         auto=NOQ(W(["qui", "que", "qu'", "où", "dont"], options=["qui", "que", "où", "dont"], pos=["PRON", "ADV"],
                    prev_pos=["NOUN", "PROPN", "PRON"], not_after=("cas", "heure", "heures", "ans", "jours", "mois", "temps")))),
    dict(id="fr-superlatives", level="A2", title=T("Superlatives", "Превосходная степень"), auto=NEED(W(["plus", "moins", "meilleur", "meilleure", "mieux"]), ["le", "la", "les"])),
    dict(id="fr-adverbs", level="A2", title=T("Adverbs: -ment, bien/bon, position", "Наречия: -ment, bien/bon, место в предложении"), auto=RX(r".{3,}ment", pos=["ADV"])),
    dict(id="fr-indefinites", level="A2", title=T("Quelqu'un, quelque chose, personne, rien, tout", "Quelqu'un, quelque chose, personne, rien, tout"),
         auto=W(["quelqu'un", "quelque chose", "personne", "rien", "tout", "tous", "toute", "toutes", "chaque", "plusieurs", "aucun", "aucune"])),
    dict(id="fr-stressed", level="A2", title=T("Stressed and possessive pronouns (moi, le mien)", "Ударные и притяжательные местоимения (moi, le mien)"),
         auto=W(["moi", "toi", "eux", "mien", "mienne", "tien", "tienne", "sien", "sienne"], pos=["PRON"])),
    dict(id="fr-health", level="A2", title=T("Health and the body: avoir mal à", "Здоровье и тело: avoir mal à"),
         auto=NEED(W(["à la", "au", "aux", "à l'"], options=["à la", "au", "aux", "à l'"]), ["mal"])),
    dict(id="fr-time-prep", level="A2", title=T("Depuis, pendant, il y a, dans, pour", "Depuis, pendant, il y a, dans, pour"),
         auto=W(["depuis", "pendant"], options=["depuis", "pendant", "il y a", "dans"])),
    # ---------------- B1 ----------------
    dict(id="fr-subj-forms", level="B1", title=T("Present subjunctive: forms; il faut que", "Сослагательное наклонение (subjonctif): формы; il faut que"),
         auto=V(["subj"]), tenses=["subj"]),
    dict(id="fr-subj-uses", level="B1", title=T("Subjunctive after wishes and feelings", "Subjonctif после желания и чувств"),
         auto=NEED(V(["subj"]), ["faut que", "veux que", "voudrais que", "souhaite que", "préfère que", "content que", "heureux que", "dommage que", "peur que", "aimerais que", "faut qu'", "veut que"])),
    dict(id="fr-subj-doubt", level="B1", title=T("Subjunctive after doubt; je pense que vs je ne pense pas que", "Subjonctif после сомнения; je pense que / je ne pense pas que"),
         auto=NEED(VC("subj", "pres", only_a=True), ["pense pas que", "crois pas que", "doute que", "possible que", "pas sûr que", "impossible que"])),
    dict(id="fr-subj-conj", level="B1", title=T("Pour que, bien que, avant que, à condition que", "Pour que, bien que, avant que, à condition que"),
         auto=NEED(V(["subj"]), ["pour que", "pour qu'", "bien que", "avant que", "à condition que", "sans que", "jusqu' à ce que", "à moins que"])),
    dict(id="fr-pqp", level="B1", title=T("The plus-que-parfait", "Плюсквамперфект (plus-que-parfait)"), auto=COMP("pqp", aux=AUX), tenses=["pqp"]),
    dict(id="fr-si", level="B1", title=T("If-clauses (si + présent / imparfait)", "Условные предложения (si + présent / imparfait)"),
         auto=NEED(ANY(V(["impf"]), V(["cond"])), ["si", "s'"])),
    dict(id="fr-reported", level="B1", title=T("Reported speech", "Косвенная речь"),
         auto=NEED(V(["impf", "cond"]), ["a dit que", "a dit qu'", "disait que", "a demandé si", "a répondu que", "m' a dit que"])),
    dict(id="fr-relatives-2", level="B1", title=T("Dont, ce qui, ce que, lequel", "Dont, ce qui, ce que, lequel"),
         auto=W(["dont", "ce qui", "ce que", "ce qu'", "lequel", "laquelle", "lesquels", "lesquelles", "auquel", "duquel"])),
    dict(id="fr-gerondif", level="B1", title=T("The gérondif (en + -ant)", "Деепричастие (gérondif: en + -ant)"),
         auto=NEED(M(["VERB", "AUX"], ["VerbForm=Part", "Tense=Pres"]), ["en"]), tenses=["ppres"]),
    dict(id="fr-passive", level="B1", title=T("The passive voice", "Страдательный залог"),
         auto=NEED(M(["VERB"], ["VerbForm=Part", "Tense=Past"]), ["par"])),
    dict(id="fr-futur-ant", level="B1", title=T("The futur antérieur", "Предбудущее время (futur antérieur)"), auto=COMP("futant", aux=AUX), tenses=["futant"]),
    dict(id="fr-connectors", level="B1", title=T("Linking words: donc, car, pourtant, cependant…", "Связки: donc, car, pourtant, cependant…"),
         auto=W(["cependant", "pourtant", "donc", "alors", "car", "puisque", "ensuite", "enfin", "d'abord", "par contre"])),
    dict(id="fr-causatif", level="B1", title=T("Faire + infinitive; laisser + infinitive", "Faire + инфинитив; laisser + инфинитив")),
    # ---------------- B2 ----------------
    dict(id="fr-cond-passe", level="B2", title=T("Past conditional; si + plus-que-parfait", "Прошедшее условное; si + plus-que-parfait"),
         auto=ANY(COMP("condp", aux=AUX), COMP("pqp", aux=AUX)), tenses=["condp"]),
    dict(id="fr-subj-passe", level="B2", title=T("Past subjunctive", "Прошедшее сослагательное (subjonctif passé)"), auto=COMP("subjp", aux=AUX), tenses=["subjp"]),
    dict(id="fr-participe", level="B2", title=T("Present participle and participle clauses", "Причастие настоящего времени и причастные обороты"),
         auto=M(["VERB", "AUX"], ["VerbForm=Part", "Tense=Pres"])),
    dict(id="fr-accord-pp", level="B2", title=T("Past participle agreement", "Согласование причастия прошедшего времени"),
         auto=M(["VERB"], ["VerbForm=Part", "Tense=Past", "Gender=Fem"])),
    dict(id="fr-mise-en-relief", level="B2", title=T("Emphasis: c'est … qui / c'est … que", "Выделение: c'est … qui / c'est … que"),
         auto=NEED(W(["qui", "que", "qu'"]), ["c' est", "c' était", "ce sont"])),
    dict(id="fr-concession", level="B2", title=T("Concession and contrast: bien que, même si, alors que", "Уступка и противопоставление: bien que, même si, alors que"),
         auto=W(["bien que", "bien qu'", "même si", "alors que", "tandis que", "pourtant", "malgré", "quoique"])),
    dict(id="fr-cause", level="B2", title=T("Cause and consequence", "Причина и следствие"),
         auto=W(["puisque", "comme", "car", "grâce à", "à cause de", "si bien que", "de sorte que", "c' est pourquoi", "donc"])),
    dict(id="fr-hypothese", level="B2", title=T("Hypothesis: au cas où, à condition que, à moins que", "Гипотеза: au cas où, à condition que, à moins que"),
         auto=NEED(V(["subj", "cond"]), ["au cas où", "à condition que", "à moins que", "pourvu que", "en admettant que"])),
    dict(id="fr-nominalisation", level="B2", title=T("Nominalisation and formal style", "Номинализация и формальный стиль")),
    dict(id="fr-discourse", level="B2", title=T("Discourse markers", "Дискурсивные маркеры"),
         auto=W(["néanmoins", "toutefois", "en revanche", "par conséquent", "en effet", "d'ailleurs", "ainsi", "bref", "en fait", "de toute façon"])),
    dict(id="fr-pronominaux", level="B2", title=T("Pronominal verbs: passive and reciprocal; se faire, se laisser", "Местоименные глаголы: пассив и взаимность; se faire, se laisser"),
         auto=W(["se", "s'", "nous", "vous"], pos=["PRON"])),
    # ---------------- C1 ----------------
    dict(id="fr-passe-simple", level="C1", title=T("The passé simple (reading)", "Простое прошедшее (passé simple) — для чтения"), auto=V(["ps"]), tenses=["ps"]),
    dict(id="fr-literary", level="C1", title=T("Literary tenses and the imperfect subjunctive", "Литературные времена и subjonctif imparfait")),
    dict(id="fr-negation-2", level="C1", title=T("Advanced negation; the expletive ne", "Сложное отрицание; ne explétif"),
         auto=W(["guère", "nullement", "aucunement", "ni", "nulle part"])),
    dict(id="fr-registre", level="C1", title=T("Registers: formal, everyday, colloquial, verlan", "Регистры: официальный, нейтральный, разговорный, верлан")),
    dict(id="fr-idioms", level="C1", title=T("Idioms and fixed expressions", "Идиомы и устойчивые выражения")),
    dict(id="fr-francophonie", level="C1", title=T("French around the world: Belgium, Switzerland, Québec, Africa", "Французский в мире: Бельгия, Швейцария, Квебек, Африка")),
]


def U(n, level, title, topics=(), words=""):
    return dict(id=f"u{n:03d}", level=level, title=title, topics=list(topics), words=[w.strip() for w in words.split(",")] if words else [])


def PACK(n, level):
    return dict(id=f"u{n:03d}", level=level, title="", topics=[], words=[], pack=True)


UNITS = [
    # ---------------- A1 ----------------
    U(1, "A1", T("Hello! Sounds and greetings", "Здравствуйте! Звуки и приветствия"), ["fr-sounds"],
      "bonjour,bonsoir,salut:intj,au revoir,merci:intj,merci beaucoup,s'il vous plaît,s'il te plaît,oui,non,pardon:intj,excusez-moi,de rien,à bientôt,à demain,enchanté,ça va,monsieur,madame,ami"),
    U(2, "A1", T("Who are you? Pronouns and être", "Кто вы? Местоимения и être"), ["fr-etre"],
      "je,tu,il,elle,on,nous,vous,ils,elles,être,de:prep,et,étudiant,professeur,médecin,français:adj,anglais:adj,russe:adj,nom,s'appeler"),
    U(3, "A1", T("Things around us: gender and articles", "Предметы вокруг: род и артикли"), ["fr-articles", "fr-indef"],
      "le:det,la:det,un:det,une,maison,livre,table,voiture,chien,chat,ville,rue,jour,main,eau,porte,fenêtre,homme,femme,enfant,garçon,fille"),
    U(4, "A1", T("Describing people and things", "Описание людей и предметов"), ["fr-adjectives"],
      "grand,petit,bon:adj,mauvais,nouveau:adj,vieux:adj,beau:adj,joli,jeune:adj,gentil,facile,difficile,rouge:adj,bleu:adj,vert,blanc:adj,noir:adj,très,content"),
    U(5, "A1", T("To have: avoir", "Иметь: avoir"), ["fr-avoir"],
      "avoir,an,frère,sœur,fils,il y a,avoir faim,avoir soif,avoir froid,avoir chaud,avoir peur,avoir raison,avoir besoin de,avoir envie de,avoir sommeil"),
    U(6, "A1", T("Everyday actions: -er verbs", "Повседневные действия: глаголы на -er"), ["fr-er-verbs"],
      "parler,aimer,habiter,travailler,regarder,écouter,chercher,trouver,donner,manger,jouer,chanter,danser,acheter,appeler,commencer,arriver,entrer,rester,penser"),
    U(7, "A1", T("Saying no: negation", "Отрицание"), ["fr-negation"],
      "ne ... pas,ne ... jamais,ne ... rien,ne ... plus,ne ... personne,jamais,rien,personne:pron,toujours,aussi"),
    U(8, "A1", T("Asking questions", "Задаём вопросы"), ["fr-questions"],
      "qui,quoi,où,quand,comment:adv,pourquoi,combien,quel,est-ce que,qu'est-ce que,parce que,question,réponse"),
    U(9, "A1", T("Family", "Семья"), ["fr-possessives"],
      "famille,père,mère,parent,grand-père,grand-mère,oncle,tante,cousin,mari,mon,ma,mes,ton:det,ta,son:det,sa,notre,votre,leur:det"),
    U(10, "A1", T("This and that; where things are", "Этот и тот; где что находится"), ["fr-demonstratives"],
      "ce:det,cette,ces,cet,ici,là,là-bas,près de,loin de,à côté de,en face de,devant:prep,derrière:prep,sur,sous,dans,entre"),
    U(11, "A1", T("Numbers, prices and the time", "Числа, цены и время"), ["fr-numbers"],
      "deux,trois,quatre,cinq,six,sept,huit,neuf:num,dix,onze,douze,vingt,trente,cent,mille:num,heure,minute,midi,minuit,quart,euro,prix,coûter"),
    U(12, "A1", T("Days, months and dates", "Дни, месяцы и даты"), ["fr-dates"],
      "lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche,semaine,mois,année,aujourd'hui,demain,hier,matin,soir,nuit,week-end"),
    U(13, "A1", T("Going places: aller and venir", "Куда идём: aller и venir"), ["fr-aller-venir"],
      "aller,venir,gare,aéroport,train,bus,avion,métro,école,magasin,banque,plage,pays,pied,vélo"),
    U(14, "A1", T("Plans and things that just happened", "Планы и то, что только что произошло"), ["fr-futur-proche"],
      "bientôt,tout de suite,maintenant,déjà,encore,tard,tôt,voyage,vacance,projet"),
    U(15, "A1", T("More verbs: -ir, -re and irregulars", "Ещё глаголы: -ir, -re и неправильные"), ["fr-ir-re"],
      "finir,choisir,réussir,vendre,attendre,répondre,entendre,perdre,faire,prendre,mettre,dire,lire,écrire,boire,comprendre,apprendre"),
    U(16, "A1", T("Want, can, must, know", "Хотеть, мочь, быть должным, знать"), ["fr-modals"],
      "vouloir,pouvoir:verb,devoir:verb,savoir:verb,connaître,falloir,il faut"),
    U(17, "A1", T("Food and quantities", "Еда и количество"), ["fr-partitive"],
      "pain,vin,bière,café,thé,lait,fromage,viande,poisson,poulet,fruit,pomme,sucre,sel,beaucoup de,un peu,assez,trop,restaurant,repas,déjeuner:noun,dîner:noun"),
    U(18, "A1", T("My daily routine", "Мой распорядок дня"), ["fr-reflexive"],
      "se lever,se réveiller,se coucher,se laver,s'habiller,se doucher,se brosser,se promener,s'asseoir,se dépêcher,se reposer,s'amuser,dent,cheveu,lit"),
    U(19, "A1", T("Instructions and directions", "Инструкции и как пройти"), ["fr-imperative"],
      "tourner,continuer,traverser,droite,gauche:noun,droit:adv,place,coin,feu,pont,carte"),
    U(20, "A1", T("Weather and seasons", "Погода и времена года"), ["fr-weather"],
      "temps,il fait beau,il pleut,soleil,pluie,neige,vent,nuage,chaud,froid:adj,été,hiver,printemps,automne,degré,ciel"),
    U(21, "A1", T("Clothes, shopping and comparisons", "Одежда, покупки и сравнение"), ["fr-comparatives"],
      "vêtement,chemise,pantalon,robe,chaussure,veste,manteau,cher:adj,argent,plus,moins:adv,meilleur:adj,mieux:adv,taille"),
    # ---------------- A2 ----------------
    U(22, "A2", T("What I did: passé composé with avoir", "Что я сделал: passé composé с avoir"), ["fr-pc-avoir"],
      "dernier,visiter,oublier,trouver,perdre,voyage"),
    U(23, "A2", T("Where I went: passé composé with être", "Куда я ходил: passé composé с être"), ["fr-pc-etre"],
      "partir,sortir,monter,descendre,naître,mourir,tomber,retourner,devenir,rentrer"),
    U(24, "A2", T("When I was a child: the imparfait", "Когда я был ребёнком: imparfait"), ["fr-imparfait"],
      "enfance,autrefois,souvent,chaque,village,jouet"),
    U(25, "A2", T("Telling stories", "Рассказываем истории"), ["fr-pc-impf"],
      "soudain:adv,pendant,lorsque,histoire,moment,fois"),
    U(26, "A2", T("At home: direct object pronouns", "Дома: прямые дополнения"), ["fr-cod"],
      "chambre,cuisine,salon,chaise,fauteuil,clé,appartement,étage,mur,meuble,placard"),
    U(27, "A2", T("Giving and telling: lui, leur", "Давать и говорить: lui, leur"), ["fr-coi"],
      "offrir,prêter,envoyer,téléphoner,demander,cadeau,lettre,message,anniversaire,fête"),
    U(28, "A2", T("Y and en", "Местоимения y и en"), ["fr-y-en"],
      "y,en:pron,s'occuper de,revenir"),
    U(29, "A2", T("The future", "Будущее"), ["fr-futur"],
      "avenir,prochain:adj,carrière,université,métier,plan"),
    U(30, "A2", T("Would you…? The conditional", "Вы бы…? Условное наклонение"), ["fr-conditionnel"],
      "conseil,idée,avis,aimer"),
    U(31, "A2", T("Who, which, where: relative pronouns", "Который, где: относительные местоимения"), ["fr-relatives"],
      "dont,endroit,lieu,chose,raison,façon"),
    U(32, "A2", T("The best and the worst", "Лучший и худший"), ["fr-superlatives"],
      "célèbre,important,intéressant,drôle,riche,pauvre:adj,dangereux,tranquille"),
    U(33, "A2", T("How and how often: adverbs", "Как и как часто: наречия"), ["fr-adverbs"],
      "vite,lentement,facilement,vraiment,seulement,parfois,presque"),
    U(34, "A2", T("Someone, something, nobody", "Кто-то, что-то, никто"), ["fr-indefinites"],
      "quelqu'un,quelque chose,chaque,aucun:det,certain:det,autre:adj,même:adj"),
    U(35, "A2", T("Me, you, mine, yours", "Мне, тебе, мой, твой"), ["fr-stressed"],
      "moi,toi,lui,eux,sac,valise,téléphone,portable:adj"),
    U(36, "A2", T("Health and the body", "Здоровье и тело"), ["fr-health"],
      "tête,ventre,dos,bras,jambe,oreille,gorge,malade:adj,fièvre,médicament"),
    U(37, "A2", T("Since, for, ago", "С тех пор, в течение, назад"), ["fr-time-prep"],
      "depuis:prep,avant:prep,après:prep,vers"),
    # ---------------- B1 ----------------
    U(38, "B1", T("The subjunctive: forms", "Subjonctif: образование"), ["fr-subj-forms"]),
    U(39, "B1", T("Wishes and feelings", "Желания и чувства"), ["fr-subj-uses"], "souhaiter,regretter,dommage"),
    U(40, "B1", T("Opinions and doubts", "Мнения и сомнения"), ["fr-subj-doubt"], "douter,possible,impossible,sûr"),
    U(41, "B1", T("So that, although, before", "Чтобы, хотя, прежде чем"), ["fr-subj-conj"]),
    U(42, "B1", T("Before that: plus-que-parfait", "До того: plus-que-parfait"), ["fr-pqp"]),
    U(43, "B1", T("If…: conditional sentences", "Если бы…: условные предложения"), ["fr-si"]),
    U(44, "B1", T("He said that…", "Он сказал, что…"), ["fr-reported"], "raconter,expliquer,répondre,demander"),
    U(45, "B1", T("Dont, ce qui, ce que, lequel", "Dont, ce qui, ce que, lequel"), ["fr-relatives-2"], "lequel"),
    U(46, "B1", T("While doing: the gérondif", "Делая: gérondif"), ["fr-gerondif"]),
    U(47, "B1", T("The passive", "Пассив"), ["fr-passive"]),
    U(48, "B1", T("Will have done: futur antérieur", "Будет сделано: futur antérieur"), ["fr-futur-ant"]),
    U(49, "B1", T("Linking ideas", "Связываем мысли"), ["fr-connectors"], "cependant,pourtant,donc,car,puisque"),
    U(50, "B1", T("Getting things done: faire faire", "Поручить сделать: faire faire"), ["fr-causatif"]),
    *[PACK(n, "B1") for n in range(51, 57)],
    # ---------------- B2 ----------------
    U(57, "B2", T("What would have happened", "Что было бы"), ["fr-cond-passe"]),
    U(58, "B2", T("Past subjunctive", "Прошедшее сослагательное"), ["fr-subj-passe"]),
    U(59, "B2", T("Participles", "Причастия"), ["fr-participe"]),
    U(60, "B2", T("Participle agreement", "Согласование причастий"), ["fr-accord-pp"]),
    U(61, "B2", T("Emphasis", "Выделение"), ["fr-mise-en-relief"]),
    U(62, "B2", T("Contrast and concession", "Противопоставление и уступка"), ["fr-concession"]),
    U(63, "B2", T("Cause and consequence", "Причина и следствие"), ["fr-cause"]),
    U(64, "B2", T("Hypotheses", "Гипотезы"), ["fr-hypothese"]),
    U(65, "B2", T("Formal style", "Формальный стиль"), ["fr-nominalisation"]),
    U(66, "B2", T("Discourse markers", "Дискурсивные маркеры"), ["fr-discourse"]),
    U(67, "B2", T("Pronominal verbs II", "Местоименные глаголы II"), ["fr-pronominaux"]),
    *[PACK(n, "B2") for n in range(68, 80)],
    # ---------------- C1 ----------------
    U(80, "C1", T("The passé simple", "Passé simple"), ["fr-passe-simple"]),
    U(81, "C1", T("Literary French", "Литературный французский"), ["fr-literary"]),
    U(82, "C1", T("Advanced negation", "Сложное отрицание"), ["fr-negation-2"]),
    U(83, "C1", T("Registers and slang", "Регистры и сленг"), ["fr-registre"]),
    U(84, "C1", T("Idioms", "Идиомы"), ["fr-idioms"]),
    U(85, "C1", T("French around the world", "Французский в мире"), ["fr-francophonie"]),
    *[PACK(n, "C1") for n in range(86, 146)],
]
