"""Spanish course (for English speakers): grammar topics and units A1 → C1.

Each topic: id, level, title, auto (selector producing gap exercises from real sentences), tenses (unlocked conjugation drills).
Each unit: id, level, title, topics, words (theme vocabulary; the rest is filled by frequency), pack=True for vocabulary-only units.
Explanations: content/es/grammar/<topic>.en.md ; drills: content/es/drills/<topic>.txt
"""
from sel import ANY, COMP, M, NEED, NEGIMP, NOQ, V, VC, VL, W

PRES = ["pres"]

TOPICS = [
    # ---------------- A1 ----------------
    dict(id="es-sounds", level="A1", title="Sounds, spelling and stress"),
    dict(id="es-ser", level="A1", title="Subject pronouns and ser (to be)", auto=V(PRES, lemmas=["ser"]), tenses=PRES),
    dict(id="es-gender", level="A1", title="Nouns: gender, plural and articles",
         auto=W(["el", "la", "los", "las"], options=["el", "la", "los", "las"], pos=["DET"])),
    dict(id="es-indef-art", level="A1", title="Un, una, unos, unas",
         auto=W(["un", "una", "unos", "unas"], options=["un", "una", "unos", "unas"], pos=["DET"])),
    dict(id="es-adjectives", level="A1", title="Adjectives: agreement and position", auto=M(["ADJ"], ["Number=Plur"], hint=None)),
    dict(id="es-estar", level="A1", title="Estar, and ser vs estar (basics)", auto=VL("ser", "estar", PRES), tenses=PRES),
    dict(id="es-hay-numbers", level="A1", title="Hay and numbers 0–100", auto=W(["hay"], hint="haber")),
    dict(id="es-tener", level="A1", title="Tener and expressions with tener", auto=V(PRES, lemmas=["tener"])),
    dict(id="es-present-ar", level="A1", title="Present tense: regular -ar verbs",
         auto=V(PRES, lemmas=["hablar", "trabajar", "estudiar", "llamar", "tomar", "comprar", "llegar", "necesitar", "mirar",
                              "escuchar", "esperar", "cocinar", "bailar", "cantar", "pagar", "ayudar", "entrar", "buscar", "usar",
                              "viajar", "caminar", "ganar", "dejar", "llevar", "quedar", "pasar", "gustar", "amar", "odiar"]),
         tenses=PRES),
    dict(id="es-present-er-ir", level="A1", title="Present tense: regular -er and -ir verbs",
         auto=V(PRES, lemmas=["comer", "beber", "vivir", "escribir", "leer", "aprender", "comprender", "abrir", "recibir",
                              "deber", "correr", "creer", "vender", "subir", "decidir", "compartir", "existir", "romper"])),
    dict(id="es-questions", level="A1", title="Questions and negation",
         auto=W(["qué", "quién", "quiénes", "dónde", "cuándo", "cómo", "cuánto", "cuánta", "cuántos", "cuántas", "cuál", "cuáles"])),
    dict(id="es-possessives", level="A1", title="Possessive adjectives (mi, tu, su…)",
         auto=W(["mi", "mis", "tu", "tus", "su", "sus", "nuestro", "nuestra", "nuestros", "nuestras"], pos=["DET"])),
    dict(id="es-demonstratives", level="A1", title="Demonstratives: este, ese, aquel",
         auto=W(["este", "esta", "estos", "estas", "ese", "esa", "esos", "esas", "aquel", "aquella", "aquellos", "aquellas", "esto", "eso"])),
    dict(id="es-gustar", level="A1", title="Gustar and similar verbs", auto=V(PRES, lemmas=["gustar", "encantar"], hint="lemma")),
    dict(id="es-time", level="A1", title="Telling the time, days and dates",
         auto=W(["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "hoy", "mañana", "ayer"])),
    dict(id="es-reflexive", level="A1", title="Reflexive verbs and daily routine",
         auto=W(["me", "te", "se", "nos", "os"], pos=["PRON"])),
    dict(id="es-ir", level="A1", title="Ir, ir a + infinitive, al / del", auto=V(PRES, lemmas=["ir"]), tenses=PRES),
    dict(id="es-stem", level="A1", title="Stem-changing verbs (e→ie, o→ue, e→i)",
         auto=V(PRES, lemmas=["querer", "poder", "pensar", "empezar", "dormir", "volver", "pedir", "repetir", "entender",
                              "encontrar", "jugar", "costar", "cerrar", "preferir", "servir", "contar", "perder", "recordar",
                              "sentir", "seguir", "mostrar", "morir", "comenzar", "despertar", "mentir"])),
    dict(id="es-yo-irregular", level="A1", title="Irregular yo forms; saber vs conocer",
         auto=ANY(V(PRES, lemmas=["hacer", "poner", "salir", "traer", "conocer", "decir", "venir", "dar", "oír", "conducir", "traducir", "caer"]),
                  VL("saber", "conocer", PRES))),
    dict(id="es-weather", level="A1", title="Weather: hace, hay, está, llueve",
         auto=NEED(W(["hace", "hacía", "llueve", "nieva", "está"]), ["frío", "calor", "sol", "viento", "llueve", "nieva", "tiempo", "nublado"])),
    dict(id="es-progressive", level="A1", title="Present progressive: estar + gerund",
         auto=M(["VERB"], ["VerbForm=Ger"]), tenses=["ger"]),
    dict(id="es-comparatives", level="A1", title="Comparisons: más/menos… que, tan… como",
         auto=W(["más", "menos", "tan", "mejor", "peor", "mayor", "menor"])),
    # ---------------- A2 ----------------
    dict(id="es-do-pronouns", level="A2", title="Direct object pronouns (lo, la, los, las) and personal a",
         auto=W(["lo", "la", "los", "las"], options=["lo", "la", "los", "las"], pos=["PRON"])),
    dict(id="es-io-pronouns", level="A2", title="Indirect object pronouns and se lo",
         auto=W(["le", "les", "se lo", "se la", "se los", "se las"], pos=["PRON"])),
    dict(id="es-preterite", level="A2", title="Preterite: regular verbs",
         auto=V(["pret"], lemmas=["hablar", "trabajar", "estudiar", "llamar", "tomar", "comprar", "llegar", "comer", "beber", "vivir",
                                  "escribir", "abrir", "volver", "salir", "nacer", "visitar", "terminar", "empezar", "ayudar", "pasar",
                                  "esperar", "encontrar", "perder", "olvidar", "mirar", "escuchar", "pagar", "cambiar", "viajar", "llevar",
                                  "dejar", "entrar", "recibir", "decidir", "aprender", "conocer", "ganar", "matar", "intentar", "gustar"]),
         tenses=["pret"]),
    dict(id="es-preterite-irr", level="A2", title="Preterite: irregular verbs",
         auto=V(["pret"], lemmas=["ser", "ir", "tener", "estar", "hacer", "poder", "poner", "decir", "venir", "traer", "querer",
                                  "saber", "dar", "ver", "andar", "conducir", "pedir", "dormir", "morir", "leer", "oír", "caer", "haber"]),
         tenses=["pret"]),
    dict(id="es-imperfect", level="A2", title="The imperfect", auto=V(["impf"]), tenses=["impf"]),
    dict(id="es-pret-impf", level="A2", title="Preterite or imperfect?", auto=VC("pret", "impf")),
    dict(id="es-por-para", level="A2", title="Por and para", auto=W(["por", "para"], options=["por", "para"], pos=["ADP"])),
    dict(id="es-perfect", level="A2", title="Present perfect (he hablado)", auto=COMP("perf"), tenses=["perf", "part"]),
    dict(id="es-future", level="A2", title="The future tense", auto=V(["fut"]), tenses=["fut"]),
    dict(id="es-conditional", level="A2", title="The conditional", auto=V(["cond"]), tenses=["cond"]),
    dict(id="es-imperative", level="A2", title="Commands: tú and usted (affirmative)", auto=NOQ(V(["imp"], morph_req=("Mood=Imp",))), tenses=["imp"]),
    dict(id="es-doler", level="A2", title="Doler, parecer, interesar: more verbs like gustar",
         auto=V(PRES + ["impf", "pret"], lemmas=["doler", "parecer", "interesar", "importar", "molestar", "encantar", "faltar", "quedar"])),
    dict(id="es-indefinites", level="A2", title="Algo, nada, alguien, nadie, alguno, ninguno",
         auto=W(["algo", "nada", "alguien", "nadie", "algún", "alguna", "algunos", "algunas", "ningún", "ninguna", "nunca", "siempre", "también", "tampoco"])),
    dict(id="es-poss-pronouns", level="A2", title="Possessive pronouns (mío, tuyo, suyo…)",
         auto=W(["mío", "mía", "míos", "mías", "tuyo", "tuya", "tuyos", "tuyas", "suyo", "suya", "suyos", "suyas", "nuestro", "nuestra"], pos=["PRON", "ADJ"])),
    dict(id="es-superlatives", level="A2", title="Superlatives and -ísimo", auto=NEED(W(["más", "menos", "mejor", "peor"]), ["el", "la", "los", "las"])),
    dict(id="es-adverbs", level="A2", title="Adverbs: -mente, muy, mucho, bastante, demasiado",
         auto=ANY(M(["ADV"], [], hint=None), W(["muy", "mucho", "bastante", "demasiado"]))),
    dict(id="es-relatives", level="A2", title="Relative pronouns: que, quien, donde, lo que", auto=NOQ(W(["que", "quien", "quienes", "donde", "lo que"], pos=["PRON", "ADV"]))),
    dict(id="es-periphrases", level="A2", title="Verb phrases: tener que, hay que, acabar de, volver a, soler",
         auto=V(PRES + ["impf", "pret"], lemmas=["acabar", "volver", "soler", "tener", "deber", "empezar", "dejar"])),
    # ---------------- B1 ----------------
    dict(id="es-subj-forms", level="B1", title="Present subjunctive: forms", auto=V(["subj"]), tenses=["subj"]),
    dict(id="es-subj-wishes", level="B1", title="Subjunctive after wishes and requests",
         auto=NEED(V(["subj"]), ["quiero que", "quieres que", "quiere que", "espero que", "ojalá", "prefiero que", "pide que", "necesito que", "deseo que"])),
    dict(id="es-subj-emotion", level="B1", title="Subjunctive after emotions",
         auto=NEED(V(["subj"]), ["alegra que", "gusta que", "molesta que", "sorprende que", "siento que", "miedo de que", "pena que", "lástima que", "encanta que"])),
    dict(id="es-subj-doubt", level="B1", title="Subjunctive after doubt and denial",
         auto=NEED(VC("subj", "pres", only_a=True), ["no creo que", "dudo que", "no pienso que", "es posible que", "puede que", "no es verdad que", "no estoy seguro de que", "quizás", "tal vez"])),
    dict(id="es-subj-impersonal", level="B1", title="Es importante que… impersonal expressions",
         auto=NEED(V(["subj"]), ["es importante que", "es necesario que", "es mejor que", "es posible que", "es normal que", "es raro que", "hace falta que"])),
    dict(id="es-subj-time", level="B1", title="Cuando, hasta que, antes de que + subjunctive",
         auto=NEED(VC("subj", "pres", only_a=True), ["cuando", "hasta que", "antes de que", "después de que", "en cuanto", "tan pronto como"])),
    dict(id="es-subj-purpose", level="B1", title="Para que, sin que, aunque",
         auto=NEED(V(["subj", "subj_impf"]), ["para que", "sin que", "aunque", "a fin de que"])),
    dict(id="es-subj-relative", level="B1", title="Subjunctive in relative clauses",
         auto=NEED(V(["subj"]), ["alguien que", "nadie que", "algo que", "nada que", "uno que", "una que", "alguno que", "ninguno que"])),
    dict(id="es-imperative-2", level="B1", title="Negative and formal commands; pronouns with commands",
         auto=NEGIMP(), tenses=["imp_neg"]),
    dict(id="es-pluperfect", level="B1", title="Pluperfect (había hecho)", auto=COMP("plup"), tenses=["plup"]),
    dict(id="es-subj-impf", level="B1", title="Imperfect subjunctive", auto=V(["subj_impf"]), tenses=["subj_impf"]),
    dict(id="es-si", level="B1", title="If-clauses: real and hypothetical",
         auto=NEED(ANY(V(["subj_impf"]), V(["cond"])), ["si"])),
    dict(id="es-se", level="B1", title="Se: impersonal, passive and accidental", auto=NEED(W(["se"], pos=["PRON"]), ["se"])),
    dict(id="es-reported", level="B1", title="Reported speech",
         auto=NEED(V(["impf", "cond", "plup", "subj_impf"]), ["dijo que", "dijeron que", "me dijo que", "preguntó si", "contó que", "explicó que"])),
    dict(id="es-probability", level="B1", title="Guessing and probability: future and conditional",
         auto=NEED(V(["fut", "cond"]), ["supongo", "probablemente", "quizá", "quizás", "seguramente", "estará", "será", "tendrá", "serían", "sería"])),
    dict(id="es-relatives-2", level="B1", title="El que, el cual, cuyo, lo cual",
         auto=W(["el que", "la que", "los que", "las que", "el cual", "la cual", "los cuales", "las cuales", "cuyo", "cuya", "cuyos", "cuyas", "lo cual"])),
    dict(id="es-connectors", level="B1", title="Linking ideas: sin embargo, por eso, además…",
         auto=W(["sin embargo", "por eso", "además", "aunque", "así que", "por lo tanto", "en cambio", "es decir", "incluso", "pues"])),
    # ---------------- B2 ----------------
    dict(id="es-subj-perf", level="B2", title="Perfect subjunctive (haya hecho)", auto=COMP("subj_perf"), tenses=["subj_perf"]),
    dict(id="es-si-past", level="B2", title="If I had known…: pluperfect subjunctive and conditional perfect",
         auto=ANY(COMP("subj_plup"), COMP("cond_perf")), tenses=["subj_plup", "cond_perf"]),
    dict(id="es-sequence", level="B2", title="Sequence of tenses", auto=NEED(VC("subj_impf", "subj", only_a=True), ["que"])),
    dict(id="es-passive", level="B2", title="The passive: ser + participle, estar + participle",
         auto=NEED(V(["pres", "pret", "impf", "fut"], lemmas=["ser", "estar"]), ["por"])),
    dict(id="es-change", level="B2", title="Verbs of change: ponerse, volverse, hacerse, quedarse",
         auto=V(PRES + ["pret", "impf", "perf"], lemmas=["poner", "volver", "hacer", "quedar", "convertir", "llegar"])),
    dict(id="es-prep-verbs", level="B2", title="Verbs with prepositions: pensar en, soñar con, depender de…",
         auto=NEED(W(["en", "con", "de", "a"], options=["en", "con", "de", "a"], pos=["ADP"]),
                   ["pienso", "piensa", "pensar", "sueño", "soñar", "depende", "acuerdo", "acuerdas", "olvidé", "casarse", "casó", "enamoró", "confío", "trata"])),
    dict(id="es-periphrases-2", level="B2", title="Llevar, seguir, ponerse a, dejar de, estar a punto de",
         auto=V(PRES + ["pret", "impf"], lemmas=["llevar", "seguir", "dejar", "ponerse", "acabar", "llegar"])),
    dict(id="es-lo", level="B2", title="Lo neutro: lo bueno, lo que, lo + adjective + que", auto=W(["lo", "lo que"], pos=["DET", "PRON"])),
    dict(id="es-subj-conditions", level="B2", title="A menos que, con tal de que, en caso de que",
         auto=NEED(V(["subj", "subj_impf"]), ["a menos que", "con tal de que", "en caso de que", "siempre que", "a no ser que"])),
    dict(id="es-ser-estar-2", level="B2", title="Ser and estar: changes in meaning", auto=VL("ser", "estar", ["pres", "impf", "pret"])),
    dict(id="es-pronoun-placement", level="B2", title="Where pronouns go: before the verb or attached",
         auto=W(["me", "te", "lo", "la", "le", "nos", "los", "las", "les", "se"], pos=["PRON"])),
    dict(id="es-discourse", level="B2", title="Discourse markers for speaking and writing",
         auto=W(["no obstante", "por consiguiente", "en cambio", "es decir", "o sea", "en resumen", "por cierto", "de hecho", "al fin y al cabo"])),
    # ---------------- C1 ----------------
    dict(id="es-subj-advanced", level="C1", title="Quizás, como + subjunctive, el hecho de que",
         auto=NEED(V(["subj", "subj_impf"]), ["quizás", "quizá", "tal vez", "como", "el hecho de que", "no es que", "por mucho que"])),
    dict(id="es-cleft", level="C1", title="Emphasis and cleft sentences (es aquí donde…)",
         auto=NEED(W(["quien", "donde", "cuando", "lo que", "el que", "la que"]), ["es", "fue", "era"])),
    dict(id="es-formal", level="C1", title="Formal register and the future subjunctive"),
    dict(id="es-word-formation", level="C1", title="Word formation: diminutives, augmentatives, prefixes"),
    dict(id="es-idioms", level="C1", title="Common idioms and fixed expressions"),
    dict(id="es-variation", level="C1", title="Spain and Latin America: vosotros, voseo, vocabulary"),
]


def U(n, level, title, topics=(), words=""):
    return dict(id=f"u{n:03d}", level=level, title=title, topics=list(topics), words=words.split(",") if words else [])


def PACK(n, level):
    return dict(id=f"u{n:03d}", level=level, title="", topics=[], words=[], pack=True)


UNITS = [
    # ---------------- A1 ----------------
    U(1, "A1", "Hello! Sounds and greetings", ["es-sounds"],
      "hola,adiós:intj,gracias:intj,por favor,sí:adv,no:adv,buenos días,buenas tardes,buenas noches,bien,mal,de nada,lo siento,hasta luego,mucho gusto,señor,señora,amigo,perdón:intj"),
    U(2, "A1", "Who are you? Pronouns and ser", ["es-ser"],
      "yo,tú,él,ella,usted,nosotros,vosotros,ellos,ellas,ustedes,ser,de:prep,y,estudiante,profesor,médico,inglés:adj,español:adj,nombre,llamarse"),
    U(3, "A1", "Things around us: gender and articles", ["es-gender", "es-indef-art"],
      "el:det,un:det,casa,libro,mesa,coche,perro,gato,ciudad,calle,día,mano,mapa,agua,puerta,ventana,hombre,mujer,niño,chico,chica"),
    U(4, "A1", "Describing people and things", ["es-adjectives"],
      "grande,pequeño,bueno,malo,nuevo,viejo,bonito,alto,bajo:adj,joven,simpático,fácil,difícil,rojo,azul,verde,blanco,negro,muy"),
    U(5, "A1", "Where and how: estar", ["es-estar"],
      "estar,aquí,allí,ahí,cansado,contento,triste,enfermo,ocupado,listo,en,con,trabajo,oficina,hotel,feliz,abierto,cerrado"),
    U(6, "A1", "Hay and numbers", ["es-hay-numbers"],
      "haber,uno:num,dos,tres,cuatro,cinco,seis,siete,ocho,nueve,diez,veinte,cien,mil,número,cuánto,mucho:det,poco:det,cero"),
    U(7, "A1", "To have: tener", ["es-tener"],
      "tener,hambre,sed,frío:noun,calor,miedo,razón,prisa,sueño,año,hermano,hijo,coche,tiempo"),
    U(8, "A1", "Everyday actions: -ar verbs", ["es-present-ar"],
      "hablar,trabajar,estudiar,llamar,tomar,comprar,llegar,necesitar,mirar,escuchar,esperar,cocinar,bailar,cantar,pagar,ayudar,entrar,buscar,usar"),
    U(9, "A1", "More actions: -er and -ir verbs", ["es-present-er-ir"],
      "comer,beber,vivir,escribir,leer,aprender,comprender,abrir,recibir,deber,correr,creer,vender,subir,decidir,compartir"),
    U(10, "A1", "Asking questions", ["es-questions"],
      "qué,quién,dónde,cuándo,cómo,cuál,por qué,porque,nunca,nada,nadie,también,tampoco,pregunta,respuesta"),
    U(11, "A1", "Family", ["es-possessives"],
      "familia,padre,madre,padres,hermana,hija,abuelo,abuela,tío,tía,primo,esposo,esposa,mi,tu:det,su,nuestro,novio,novia,bebé"),
    U(12, "A1", "This, that, here, there", ["es-demonstratives"],
      "este:det,ese:det,aquel,esto,eso,cosa,lugar,ahora,allá,cerca,lejos,otro,mismo,izquierda,derecha"),
    U(13, "A1", "Food and what you like", ["es-gustar"],
      "gustar,encantar,comida,pan,carne,pescado,fruta,manzana,leche,café,té,vino,cerveza,queso,huevo,arroz,restaurante,desayuno,cena,almuerzo"),
    U(14, "A1", "Time, days and dates", ["es-time"],
      "hora,minuto,lunes,martes,miércoles,jueves,viernes,sábado,domingo,hoy,mañana:adv,ayer,semana,mes,tarde:noun,noche,temprano,medio"),
    U(15, "A1", "My daily routine", ["es-reflexive"],
      "levantarse,despertarse,ducharse,vestirse,acostarse,lavarse,sentarse,sentirse,quedarse,irse,baño,cama,ropa,diente,pelo"),
    U(16, "A1", "Going places", ["es-ir"],
      "ir,a:prep,viaje,tren,autobús,avión,estación,aeropuerto,playa,país,museo,parque,mercado,banco,billete,mapa"),
    U(17, "A1", "Stem-changing verbs", ["es-stem"],
      "querer,poder,pensar,empezar,dormir,volver,pedir,repetir,entender,encontrar,jugar,costar,cerrar,preferir,servir,contar,perder,recordar"),
    U(18, "A1", "Irregular verbs; saber and conocer", ["es-yo-irregular"],
      "hacer,poner,salir,traer,conocer,saber,decir,venir,ver,dar,oír,conducir,traducir"),
    U(19, "A1", "Weather and seasons", ["es-weather"],
      "sol,lluvia,llover,nevar,nieve,viento,nube,invierno,verano,primavera,otoño,temperatura,grado,cielo"),
    U(20, "A1", "Right now: estar + -ando / -iendo", ["es-progressive"],
      "momento,todavía,ya,mientras,siempre,a veces,normalmente,gente,música,televisión,película,juego,libro"),
    U(21, "A1", "Clothes, shopping and comparisons", ["es-comparatives"],
      "ropa,camisa,pantalón,zapato,vestido,falda,chaqueta,precio,dinero,tienda,barato,caro,euro,talla,más,menos,mejor,peor,mayor,menor"),
    # ---------------- A2 ----------------
    U(22, "A2", "At home: direct object pronouns", ["es-do-pronouns"],
      "habitación,cocina,salón,mueble,silla,sofá,armario,lámpara,llave,piso,apartamento,jardín,pared,suelo"),
    U(23, "A2", "Giving and telling: indirect objects", ["es-io-pronouns"],
      "dar,regalar,mandar,enviar,prestar,explicar,enseñar,regalo,carta,mensaje,correo,cumpleaños,fiesta"),
    U(24, "A2", "Yesterday: the preterite", ["es-preterite"],
      "anoche,pasado,último,visitar,terminar,nacer,morir,olvidar,cambiar,intentar,decidir"),
    U(25, "A2", "What happened? Irregular preterites", ["es-preterite-irr"],
      "accidente,noticia,problema,policía,hospital,andar,suceder,ocurrir,pasar"),
    U(26, "A2", "When I was a child: the imperfect", ["es-imperfect"],
      "infancia,pueblo,escuela,colegio,maestro,juguete,vecino,antes,cada,soler"),
    U(27, "A2", "Telling stories", ["es-pret-impf"],
      "de repente,entonces,luego,después,cuando,historia,cuento,vez,final,principio"),
    U(28, "A2", "Work, por and para", ["es-por-para"],
      "por,para,empresa,jefe,reunión,proyecto,compañero,sueldo,cliente,contrato,negocio"),
    U(29, "A2", "Have you ever…? Present perfect", ["es-perfect"],
      "alguna vez,experiencia,mundo,extranjero,idioma,lengua,viajar,probar"),
    U(30, "A2", "Plans and the future", ["es-future"],
      "futuro,plan,próximo,pronto,quizás,tal vez,seguro,probablemente,vida,carrera,universidad"),
    U(31, "A2", "Would you…? The conditional", ["es-conditional"],
      "consejo,idea,opinión,ayuda,favor,deber,importar"),
    U(32, "A2", "Instructions and directions", ["es-imperative"],
      "receta,cortar,mezclar,añadir,girar,seguir,recto,esquina,semáforo,cruzar"),
    U(33, "A2", "Health and the body", ["es-doler"],
      "doler,cabeza,estómago,espalda,brazo,pierna,pie,ojo,oído,garganta,farmacia,medicina,fiebre,sano,cuerpo"),
    U(34, "A2", "Something and nothing", ["es-indefinites"],
      "algo,alguien,alguno,ninguno,jamás,cualquier,todo,cada"),
    U(35, "A2", "Mine and yours", ["es-poss-pronouns"],
      "mío,tuyo,suyo,maleta,bolso,teléfono,cartera,paraguas,gafas"),
    U(36, "A2", "The best and the worst", ["es-superlatives"],
      "famoso,importante,interesante,aburrido,divertido,rico,pobre,peligroso,tranquilo,ruidoso"),
    U(37, "A2", "How and how often", ["es-adverbs"],
      "rápidamente,despacio,rápido,casi,bastante,demasiado,solo,sobre todo,realmente,exactamente"),
    U(38, "A2", "Who, which, where: relative clauses", ["es-relatives"],
      "que:pron,quien,donde,persona,sitio,manera,forma"),
    U(39, "A2", "Useful verb phrases", ["es-periphrases"],
      "acabar,volver,tener que,hay que,empezar,dejar,intentar"),
    # ---------------- B1 ----------------
    U(40, "B1", "Subjunctive: forms and wishes", ["es-subj-forms", "es-subj-wishes"],
      "ojalá,esperar,desear,permitir,prohibir,aconsejar,recomendar,sugerir,exigir"),
    U(41, "B1", "Feelings: subjunctive after emotions", ["es-subj-emotion"],
      "alegrarse,molestar,sorprender,preocupar,temer,sentir,lástima,pena,sorpresa,orgulloso,emoción"),
    U(42, "B1", "Opinions and doubts", ["es-subj-doubt"],
      "dudar,parecer,posible,imposible,probable,cierto,verdad,claro,evidente,opinión"),
    U(43, "B1", "It's important that…", ["es-subj-impersonal"],
      "necesario,fundamental,raro,normal,lógico,justo,increíble,obvio,urgente"),
    U(44, "B1", "When it happens: time clauses", ["es-subj-time"],
      "hasta,antes,después,en cuanto,mientras,jubilarse,graduarse"),
    U(45, "B1", "So that, without, although", ["es-subj-purpose"],
      "aunque,a pesar de,fin,objetivo,propósito,lograr,conseguir"),
    U(46, "B1", "Looking for someone who…", ["es-subj-relative"],
      "requisito,anuncio,candidato,puesto,piso,compañero,necesitar"),
    U(47, "B1", "Commands II", ["es-imperative-2"],
      "tocar,molestar,preocuparse,olvidarse,acordarse,callarse"),
    U(48, "B1", "Before that: the pluperfect", ["es-pluperfect"],
      "ya,todavía,antes,nunca,aún"),
    U(49, "B1", "Imperfect subjunctive", ["es-subj-impf"],
      "como si,ojalá"),
    U(50, "B1", "If I won the lottery…", ["es-si"],
      "si,ganar,lotería,millón,comprar,imaginar"),
    U(51, "B1", "Se: who did it?", ["es-se"],
      "olvidarse,romperse,caerse,perderse,ocurrirse,vender,alquilar"),
    U(52, "B1", "He said that…: reported speech", ["es-reported"],
      "contar,preguntar,responder,contestar,comentar,asegurar,prometer,avisar"),
    U(53, "B1", "Guessing: probability", ["es-probability"],
      "suponer,imaginar,a lo mejor,seguramente,probablemente"),
    U(54, "B1", "Relative pronouns II", ["es-relatives-2"],
      "cuyo,cual"),
    U(55, "B1", "Linking ideas", ["es-connectors"],
      "sin embargo,por eso,además,en cambio,es decir,así que,incluso,pues"),
    PACK(56, "B1"), PACK(57, "B1"), PACK(58, "B1"), PACK(59, "B1"), PACK(60, "B1"), PACK(61, "B1"),
    # ---------------- B2 ----------------
    U(62, "B2", "Perfect subjunctive", ["es-subj-perf"]),
    U(63, "B2", "If I had known…", ["es-si-past"]),
    U(64, "B2", "Sequence of tenses", ["es-sequence"]),
    U(65, "B2", "The passive voice", ["es-passive"]),
    U(66, "B2", "Verbs of change", ["es-change"],
      "ponerse,volverse,hacerse,quedarse,convertirse"),
    U(67, "B2", "Verbs with prepositions", ["es-prep-verbs"],
      "depender,soñar,confiar,enamorarse,casarse,tratar,acordarse"),
    U(68, "B2", "Verb phrases II", ["es-periphrases-2"],
      "seguir,llevar,ponerse,punto"),
    U(69, "B2", "Lo neutro", ["es-lo"]),
    U(70, "B2", "Unless, provided that, in case", ["es-subj-conditions"]),
    U(71, "B2", "Ser and estar: meaning changes", ["es-ser-estar-2"]),
    U(72, "B2", "Pronoun placement", ["es-pronoun-placement"]),
    U(73, "B2", "Discourse markers", ["es-discourse"],
      "no obstante,o sea,de hecho,por cierto"),
    *[PACK(n, "B2") for n in range(74, 86)],
    # ---------------- C1 ----------------
    U(86, "C1", "Advanced subjunctive", ["es-subj-advanced"]),
    U(87, "C1", "Emphasis and cleft sentences", ["es-cleft"]),
    U(88, "C1", "Formal register", ["es-formal"]),
    U(89, "C1", "Word formation", ["es-word-formation"]),
    U(90, "C1", "Idioms and fixed expressions", ["es-idioms"]),
    U(91, "C1", "Spanish around the world", ["es-variation"]),
    *[PACK(n, "C1") for n in range(92, 112)],
]
